In [1]:
import torch

In [2]:
import numpy as np

In [3]:
torch.__version__

'1.9.1+cpu'

In [4]:
arr = np.array([1,2,3,4,5])

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
type(arr)

numpy.ndarray

### from_numpy

In [7]:
torch.from_numpy(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [8]:
x = torch.from_numpy(arr)

In [9]:
type(x)

torch.Tensor

### as_tensor

In [10]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [11]:
x

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [12]:
x.dtype

torch.int32

In [13]:
arr2d = np.arange(0.,10.)

In [14]:
arr2d

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [17]:
arr2d = arr2d.reshape(5,2)

In [18]:
arr2d

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [19]:
x2 = torch.from_numpy(arr2d)
x2

tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]], dtype=torch.float64)

In [20]:
arr

array([1, 2, 3, 4, 5])

In [21]:
x

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [22]:
arr[0] = 99

In [23]:
arr

array([99,  2,  3,  4,  5])

In [24]:
x

tensor([99,  2,  3,  4,  5], dtype=torch.int32)

### tensor

In [26]:
my_arr = np.arange(0,9)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
my_tensor = torch.tensor(my_arr)
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=torch.int32)

In [28]:
my_other_tensor = torch.from_numpy(my_arr)
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=torch.int32)

In [29]:
my_arr[0] = 66

In [30]:
my_arr

array([66,  1,  2,  3,  4,  5,  6,  7,  8])

In [31]:
my_other_tensor

tensor([66,  1,  2,  3,  4,  5,  6,  7,  8], dtype=torch.int32)

In [32]:
my_tensor # this is not affected by my_arr[0] = 66 assignment

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=torch.int32)