In [1]:
import torch
import numpy as np

In [3]:
a = torch.tensor([1., 2., 3.])
a

tensor([1., 2., 3.])

In [4]:
b = torch.tensor([4., 5., 6.])
b

tensor([4., 5., 6.])

In [5]:
a * b

tensor([ 4., 10., 18.])

In [6]:
a.mul(b)

tensor([ 4., 10., 18.])

In [7]:
a.dot(b)

tensor(32.)

In [10]:
a = torch.tensor([[0,2,4], [1,3,5]])
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [11]:
b = torch.tensor([[6,7], [8,9], [10,11]])
b

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

In [12]:
a.shape

torch.Size([2, 3])

In [13]:
b.shape

torch.Size([3, 2])

In [14]:
torch.mm(a,b) # matrix multiplication

tensor([[56, 62],
        [80, 89]])

In [15]:
a @ b

tensor([[56, 62],
        [80, 89]])

In [16]:
x = torch.tensor([2.,3.,4.,5.])

In [17]:
x

tensor([2., 3., 4., 5.])

In [18]:
x.norm()

tensor(7.3485)

In [19]:
x.numel()

4

In [20]:
len(x)

4

In [21]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [22]:
len(a)

2

In [23]:
a.numel()

6