In [1]:
import torch
import numpy as np

In [2]:
torch.arange(6).reshape(3,2)

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [3]:
x =  torch.arange(6).reshape(3,2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [4]:
x[1,1]

tensor(3)

In [5]:
type(x[1,1])

torch.Tensor

In [6]:
x[:,1]

tensor([1, 3, 5])

In [7]:
x[:,1:]

tensor([[1],
        [3],
        [5]])

In [8]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
x = x.reshape(2,5)
x

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [14]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
x.shape

torch.Size([10])

In [16]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
z = x.view(2,5)
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [18]:
x[0] = 66

In [19]:
x

tensor([66,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [20]:
z

tensor([[66,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]])

In [21]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
x.view(2,-1)
# infer what the 2nd dimension like reshape(2, -1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [24]:
x.reshape(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [25]:
x.view(-1,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [45]:
a = torch.tensor([1.,2.,3.,])
a

tensor([1., 2., 3.])

In [46]:
b = torch.tensor([4.,5.,6.,])
b

tensor([4., 5., 6.])

In [47]:
a.dtype

torch.float32

In [48]:
a + b

tensor([5., 7., 9.])

In [49]:
torch.add(a,b)

tensor([5., 7., 9.])

In [50]:
a.mul(b)

#a = a + b

tensor([ 4., 10., 18.])

In [51]:
a

tensor([1., 2., 3.])

In [52]:
a = a.mul(b)

In [53]:
a

tensor([ 4., 10., 18.])

In [54]:
a = torch.tensor([1.,2.,3.,])
a

tensor([1., 2., 3.])

In [55]:
a.mul_(b) # same with assignment  --> a = a.mul(b) or a = a * b

tensor([ 4., 10., 18.])

In [56]:
a

tensor([ 4., 10., 18.])