In [1]:
import torch
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])

In [3]:
arr.dtype

dtype('int32')

In [4]:
torch.tensor(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [6]:
tensor = torch.Tensor(arr) 
tensor

tensor([1., 2., 3., 4., 5.])

In [7]:
tensor.dtype

torch.float32

In [8]:
tensor = torch.FloatTensor(arr) 
tensor

tensor([1., 2., 3., 4., 5.])

In [9]:
tensor.dtype

torch.float32

In [10]:
torch.empty(2,2)

tensor([[2.1019e-44, 0.0000e+00],
        [1.4013e-45, 0.0000e+00]])

In [11]:
torch.zeros(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [12]:
torch.zeros(4,3, dtype=torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [13]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [14]:
torch.arange(0,15,3)

tensor([ 0,  3,  6,  9, 12])

In [15]:
torch.arange(0,15,3).reshape(5,1)

tensor([[ 0],
        [ 3],
        [ 6],
        [ 9],
        [12]])

In [17]:
torch.linspace(0,51,25)

tensor([ 0.0000,  2.1250,  4.2500,  6.3750,  8.5000, 10.6250, 12.7500, 14.8750,
        17.0000, 19.1250, 21.2500, 23.3750, 25.5000, 27.6250, 29.7500, 31.8750,
        34.0000, 36.1250, 38.2500, 40.3750, 42.5000, 44.6250, 46.7500, 48.8750,
        51.0000])

In [18]:
torch.linspace(0,51,25).reshape(5,5)

tensor([[ 0.0000,  2.1250,  4.2500,  6.3750,  8.5000],
        [10.6250, 12.7500, 14.8750, 17.0000, 19.1250],
        [21.2500, 23.3750, 25.5000, 27.6250, 29.7500],
        [31.8750, 34.0000, 36.1250, 38.2500, 40.3750],
        [42.5000, 44.6250, 46.7500, 48.8750, 51.0000]])

In [19]:
torch.tensor([1,2,3,4])

tensor([1, 2, 3, 4])

In [20]:
my_tensor = torch.tensor([1,2,3,4])

In [21]:
my_tensor.dtype

torch.int64

In [23]:
my_tensor = my_tensor.type(torch.int32)

In [24]:
my_tensor

tensor([1, 2, 3, 4], dtype=torch.int32)

In [25]:
torch.rand(4,5) # uniform dist

tensor([[0.7674, 0.7572, 0.5370, 0.7895, 0.0653],
        [0.1025, 0.5914, 0.9051, 0.4351, 0.3914],
        [0.8350, 0.8236, 0.5442, 0.2413, 0.3732],
        [0.5299, 0.3559, 0.4433, 0.8035, 0.0270]])

In [26]:
torch.randn(4,5) # standart normal distribution

tensor([[ 0.8905, -0.4518, -0.7195, -0.9849, -2.0160],
        [ 0.6415, -0.4332,  2.0675, -0.4631, -0.5662],
        [-0.8422,  1.5149, -0.9099,  0.6046,  0.0135],
        [ 1.3768,  1.5127, -0.6948, -0.4011, -1.0925]])

In [29]:
torch.randint(low=0, high=10, size=(4,4)) # 10 is exclusive

tensor([[4, 6, 0, 9],
        [5, 3, 0, 0],
        [9, 0, 8, 8],
        [7, 9, 9, 7]])

In [30]:
x = torch.zeros(2,4)

In [31]:
x

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
x.shape

torch.Size([2, 4])

In [33]:
torch.rand_like(x)

tensor([[0.6609, 0.1739, 0.9668, 0.0180],
        [0.0490, 0.1081, 0.4445, 0.6443]])

In [34]:
torch.randn_like(x)

tensor([[ 0.4931, -0.4416, -0.3998, -0.0464],
        [ 0.3163, -0.1687,  0.4904, -1.1506]])

In [35]:
torch.randint_like(x, low=0,high=10)

tensor([[7., 9., 4., 4.],
        [1., 4., 8., 1.]])

In [40]:
torch.manual_seed(32) # to get the same random numbers you can use seed like numpy.seed()
torch.rand(3,3)

tensor([[0.8757, 0.2721, 0.4141],
        [0.7857, 0.1130, 0.5793],
        [0.6481, 0.0229, 0.5874]])

In [43]:
torch.rand(3,3)

tensor([[0.1447, 0.1809, 0.6440],
        [0.1504, 0.7280, 0.8867],
        [0.2971, 0.7828, 0.5105]])

In [44]:
torch.rand(3,3)

tensor([[0.8187, 0.4370, 0.1878],
        [0.8781, 0.1925, 0.6161],
        [0.7849, 0.1381, 0.0455]])