### 1. Perform standard imports
Import torch and NumPy

In [1]:
import torch
import numpy as np

### 2. Set the random seed for NumPy and PyTorch both to "42"
This allows us to share the same "random" results.

In [2]:
torch.manual_seed(42)

np.random.seed(42)

### 3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive)

In [3]:
arr = np.random.randint(0,5,6)
arr

array([3, 4, 2, 4, 4, 1])

### 4. Create a tensor "x" from the array above

In [4]:
x = torch.from_numpy(arr)
x

tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)

### 5. Change the dtype of x from 'int32' to 'int64'
Note: 'int64' is also called 'LongTensor'

In [5]:
x = torch.LongTensor(arr)
x.dtype

torch.int64

In [36]:
x = x.type(torch.long)
x.dtype

torch.int64

In [37]:
x = x.type(torch.int64)
x.dtype

torch.int64

### 6. Reshape x into a 3x2 tensor
There are several ways to do this.

In [6]:
x = x.reshape(3,2)
x

tensor([[3, 4],
        [2, 4],
        [4, 1]])

### 7. Return the right-hand column of tensor x

In [7]:
x[:,1:]

tensor([[4],
        [4],
        [1]])

### 8. Without changing x, return a tensor of square values of x
There are several ways to do this.

In [8]:
x**2

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])

### 9. Create a tensor "y" with the same number of elements as x, that can be matrix-multiplied with x
Use PyTorch directly (not NumPy) to create a tensor of random integers between 0 (inclusive) and 5 (exclusive).<br>
Think about what shape it should have to permit matrix multiplication.

In [9]:
y = torch.randint(0,5,size=(2,3))
y

tensor([[2, 2, 1],
        [4, 1, 0]])

### 10. Find the matrix product of x and y

In [10]:
x.mm(y)

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])